### ISSUE TITLE
Request multi-language support

### ISSUE THREAD

**Issue by StringKe** [so1ve/clerc#22]
Switching the language according to the current system language or the parameters passed by the user

**Comment by so1ve** [comment]
Do you mean error message and help message?

**Comment by so1ve** [comment]
I haven't figured out how to do it...
First, for official plugins, implementing I18N is easy, I just need to create a @clerc/i18n package.
But how should we let users also i18n? If the user still only writes in English, then when we check the help, there may be an embarrassing situation where half of it is Chinese and half is English

**Comment by so1ve** [comment]
please look #25 :)

**Comment by so1ve** [comment]
Released v0.29.0.
